server:
  port: ${PORT:0}

spring:
  application:
    name: catalog-service

message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eurekas