server:
  port: ${PORT:0}

spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog
      host: localhost
      port: 27018
  zipkin:
      base-url: http://localhost:9411/
      enabled: true

queue:
  movie:
    name: NewMovie
  serie:
    name: NewSerie

feign:
  circuitbreaker:
    enabled: true
    group:
      enabled: true
    alphanumeric-ids:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      serie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      movie-service:
        maxAttempts: 3
        waitDuration: 10s
        retryExceptions:
          - feign.FeignException.InternalServerError
      serie-service:
        maxAttempts: 3
        waitDuration: 10s
        retryExceptions:
          - feign.FeignException.InternalServerError


message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka