server:
  port: ${PORT:8081}


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: catalog-route
          uri: lb://catalog-service
          predicates: 
            - Path=/catalog/**
        - id: movies-route
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**
        - id: serie-route
          uri: lb://serie-service
          predicates:
            - Path=/api/v1/serie/**
            

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway