server:
  port: ${PORT:0}

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/db-movie
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: MovieQueue

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka