server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri:  https://github.com/JQLaverde/esp-backend-parcial.git
          search-paths : [configurations]
          default-label: master
          force-pull: true